meta:
  coordinate_system: "unity_like"
  axes:
    x: "right"
    y: "up"
    z: "forward"
  notes:
    - "Virtual screen derived from FOV + aspect at distance d."

render:
  resolution_presets:
    quick:
      width: 960
      height: 540
    high:
      width: 2560
      height: 1440
  active_preset: "high"
  samples_per_pixel: 4
  max_depth: 9

world:
  ambient_light_rgb: [0.25, 0.25, 0.25]   # range 0–1

camera:
  presets:
    baseline:
      position: [1.0, 0.75, 3.0]
      look_at: [1.0, 0.75, 2.0]
    alt:
      position: [-3, 2, 6]
      look_at: [-1, 1.5, -20.0]
  active_camera: "baseline"
  up: [0.0, 1.0, 0.0]
  fov_y_degrees: 60.0
  focal_distance: 1.0

background:
  mode: "solid"   # later: "gradient"
  color_rgb8: [135, 206, 235]

lights:
  - type: "point"
    position: [-0.25, 3.5, 3.5]
    color_rgb: [2.0, 2.0, 2.0]
    intensity: 2.0
    range: 10.0
  - type: "point"
    position: [1.0, 2.0, 2.0]
    color_rgb: [3.0, 3.0, 3.0]
    intensity: 3.0
    range: 10.0

materials:
  sphere1:
    #reflectance and transmittance:
    kr: 0.5
    kt: 0.1

    model: "phong"
    ambient_color:  [0.2, 0.2, 0.2]
    diffuse_color:  [1.0, 1.0, 1.0]
    specular_color: [1.0, 1.0, 1.0]

    #phong_params or blinn_phong_params:
    ka: 0.1
    kd: 0.7
    ks: 0.2
    ke: 32

    #ashikhmin_shirley_params:
    # Rs: 0.2
    # Rd: 0.8
    # nu: 60
    # nv: 10

    # Texture:
    # texture: "checkerboard"
    # check_size: 0.1
    # color1: [1, 0, 0]
    # color2: [1, 1, 0]
    # Noise:
    noise: false
    noise_scale: 2.0
    noise_amp: 0.03

  sphere2:
    #reflectance and transmittance:
    kr: 0.0
    kt: 0.85

    model: "phong"
    ambient_color:  [0.1, 0.1, 0.1]
    diffuse_color:  [1.0, 1.0, 1.0]
    specular_color: [1.0, 1.0, 1.0]
    #phong_params or blinn_phong_params:
    ka: 0.1
    kd: 0.7
    ks: 0.2
    ke: 32
    #ashikhmin_shirley_params:
    # Rs: 0.05
    # Rd: 0.9
    # nu: 10
    # nv: 10

    # Texture:
    # texture: "checkerboard"
    # check_size: 1.0
    # color1: [1, 0, 0]
    # color2: [1, 1, 0]
    # texture: "bricks"
    # brick_width: 0.1
    # brick_height: 0.05
    # mortar_thickness: 0.005
    # brick_color: [0.6, 0.15, 0.1]
    # mortar_color: [0.85, 0.85, 0.85]

    # Noise:
    noise: false
    noise_scale: 2.0
    noise_amp: 0.03

  floor:
    #reflectance and transmittance:
    kr: 0.0
    kt: 0.0

    model: "phong"
    ambient_color:  [0.67, 0.2, 0.2]
    diffuse_color:  [0.67, 0.2, 0.2]
    specular_color: [0.3, 0.3, 0.3]
    ka: 0.1
    kd: 0.7
    ks: 0.1
    ke: 16

    # Texture:
    texture: "checkerboard"
    check_size: 1.0
    color1: [1, 0, 0]
    color2: [1, 1, 0]

    # Noise:
    noise: true
    noise_scale: 2.0
    noise_amp: 0.03

objects:
  - type: "sphere"
    name: "sphere1"
    center: [-0.2, 0.5, -1.0]
    radius: 0.5
    material: "sphere1"
    ior: 1.0

  - type: "sphere"
    name: "sphere2"
    center: [0.8, 0.85, 0.6]
    radius: 0.5
    material: "sphere2"
    ior: 0.95

  - type: "plane"
    name: "floor"
    point: [-17.0, 0.0, -18.0] 
    normal: [0.0, 1.0, 0.0]
    material: "floor"
    ior: 1.0
    finite: True
    unity_plane:
      base_size: 10.0            
      scale: [4.0, 1.0, 4.0] 
