meta:
  coordinate_system: "unity_like"
  axes:
    x: "right"
    y: "up"
    z: "forward"
  notes:
    - "Virtual screen derived from FOV + aspect at distance d."

render:
  resolution_presets:
    quick:
      width: 960
      height: 540
    high:
      width: 2560
      height: 1440
  active_preset: "quick"
  samples_per_pixel: 1

world:
  ambient_light_rgb: [0.1, 0.1, 0.1]   # range 0–1

camera:
  presets:
    baseline:
      position: [1.0, 0.75, 3.0]
      look_at: [1.0, 0.75, 2.0]
    alt:
      position: [-3, 2, 6]
      look_at: [-1, 1.5, -20.0]
  active_camera: "baseline"
  up: [0.0, 1.0, 0.0]
  fov_y_degrees: 60.0
  focal_distance: 1.0

background:
  mode: "solid"   # later: "gradient"
  color_rgb8: [135, 206, 235]

lights:
  - type: "point"
    position: [0.0, 3.0, 1.0]
    color_rgb: [1.0, 1.0, 1.0]
    intensity: 1.0
    range: 10.0

materials:
  sphere1:
    ambient_color:  [0.94, 0.94, 0.94]
    diffuse_color:  [0.94, 0.94, 0.94]
    specular_color: [1.0, 1.0, 1.0]
    ka: 0.1
    kd: 0.7
    ks: 0.2
    ke: 32

  sphere2:
    ambient_color:  [0.67, 0.67, 0.67]
    diffuse_color:  [0.67, 0.67, 0.67]
    specular_color: [1.0, 1.0, 1.0]
    ka: 0.1
    kd: 0.7
    ks: 0.2
    ke: 32

  floor:
    ambient_color:  [0.67, 0.2, 0.2]
    diffuse_color:  [0.67, 0.2, 0.2]
    specular_color: [0.3, 0.3, 0.3]
    ka: 0.1
    kd: 0.7
    ks: 0.1
    ke: 16

objects:
  - type: "sphere"
    name: "sphere1"
    center: [-0.2, 0.5, -1.0]
    radius: 0.5
    material: "sphere1"

  - type: "sphere"
    name: "sphere2"
    center: [0.8, 0.85, 0.6]
    radius: 0.5
    material: "sphere2"

  - type: "plane"
    name: "floor"
    point: [-18.4, 0.0, -18.0] 
    normal: [0.0, 1.0, 0.0]
    material: "floor"
    finite: True
    unity_plane:
      base_size: 10.0            
      scale: [4.0, 1.0, 4.0] 
